[package]
name = "ferris"
version = "0.1.0"
authors = ["ciusji <bqjimaster@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
log = "0.4.14"
env_logger = "0.8.3"